## K-nearest Neighbour

In [3]:
import numpy as np  
from sklearn import impute  
# create a random numpy array with 10 samples  
# and 6 features and values ranging from 1 to 15  
X = np.random.randint(1, 15, (10, 6)) 
# convert the array to float  
X = X.astype(float)  
# randomly assign 10 elements to NaN (missing)  
X.ravel()[np.random.choice(X.size, 10, replace=False)] = np.nan  

# Show Array with Missing Values
print('Array with missing values:\n', X)

# use 2 nearest neighbours to fill na values  
knn_imputer = impute.KNNImputer(n_neighbors=2)  
Y = knn_imputer.fit_transform(X) 

print('Array with imputed missing values:\n', Y)

Array with missing values:
 [[12.  7. 13.  6. nan  8.]
 [ 6.  8. 12.  2. 12.  1.]
 [10.  2.  1. 14. 11. nan]
 [13.  7. 14. 14. nan nan]
 [nan nan nan 10. 14. 11.]
 [ 2. nan  6.  4.  2.  9.]
 [14. 11.  3. 12.  7. nan]
 [ 3.  7. nan  6. 12.  9.]
 [ 1.  9.  3. 13.  2.  2.]
 [10. 10. 13. 13. 11.  3.]]
Array with imputed missing values:
 [[12.   7.  13.   6.  12.5  8. ]
 [ 6.   8.  12.   2.  12.   1. ]
 [10.   2.   1.  14.  11.  10. ]
 [13.   7.  14.  14.  12.5  7. ]
 [ 6.5  4.5  7.  10.  14.  11. ]
 [ 2.   8.   6.   4.   2.   9. ]
 [14.  11.   3.  12.   7.   7. ]
 [ 3.   7.  12.5  6.  12.   9. ]
 [ 1.   9.   3.  13.   2.   2. ]
 [10.  10.  13.  13.  11.   3. ]]
